### ISSUE TITLE
Simulation Instability with Out-of-Range Error

### ISSUE THREAD

**Issue by Teddy-van-Jerry** [mmcesim/mmcesim#1]
The generated C++ code with Armadillo can be buggy with run-time errors.
It is often seen:
```
libc++abi: terminating with uncaught exception of type std::out_of_range: Col::subvec(): indices out of bounds or incorrectly used
zsh: abort      ./OMPL
```
But the tricky points are:
- The error arises by chance, with the same binary;
- Sometimes it has something to do with the existing `_data` folder;
- With a larger simulation test number, the problem is more likely to arise.

**Comment by Teddy-van-Jerry** [comment]
With a GDB test, it can be found that:
```gdb
Thread 1 "a.out" hit Catchpoint 1 (exception thrown), 0x00007ffff62db672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#0  0x00007ffff62db672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555568271 in arma::arma_stop_bounds_error<char const*> (x=@0x7fffffffadb0: 0x5555555c2230 "Col::subvec(): indices out of bounds or incorrectly used") at /usr/include/armadillo_bits/debug.hpp:176
#2  0x000055555558b735 in arma::arma_check_bounds<char [57]> (state=true, x=...) at /usr/include/armadillo_bits/debug.hpp:504
#3  0x0000555555560bda in arma::Col<unsigned long long>::subvec (row_span=..., this=0x7fffffffb0d0) at /usr/include/armadillo_bits/Col_meat.hpp:812
#4  arma::Col<unsigned long long>::operator() (row_span=..., this=<optimized out>) at /usr/include/armadillo_bits/Col_meat.hpp:848
#5  OMP (Q=..., y=..., L=6) at OMPL.cpp:455
#6  0x0000555555565789 in f () at OMPL.cpp:647
#7  0x0000555555567da1 in main (argc=1, argv=0x7fffffffdb78) at OMPL.cpp:748
```
where line 455 of the cpp file is
```cpp
h(support(arma::span(0, j - 1))) = a; // h_{support_{0:j-1}} = a
```
So it is the problem with the OMP algorithm.

**Comment by Teddy-van-Jerry** [comment]
Solved in https://github.com/mmcesim/mmcesim/commit/0300d8830454df5019e2b25f991383b7da440a58.
